In [1]:
import polars as pl

In [2]:
DATA_DIR = "../data-parquet"

In [3]:
mcc_codes = pl.read_parquet(f"{DATA_DIR}/mcc_codes.parquet")
mcc_codes.head(5)

shape: (5, 3)
┌──────┬─────────────────────────────────────┬─────────────────────────────────────┐
│ MCC  ┆ Название                            ┆ Описание                            │
│ ---  ┆ ---                                 ┆ ---                                 │
│ i64  ┆ str                                 ┆ str                                 │
╞══════╪═════════════════════════════════════╪═════════════════════════════════════╡
│ 742  ┆ Ветеринарные услуги                 ┆ Лицензированные специалисты в ос... │
│ 763  ┆ Сельскохозяйственные кооперативы    ┆ Ассоциации и кооперативы, которы... │
│ 780  ┆ Услуги садоводства и ландшафтног... ┆ Ландшафтные архитекторы и другие... │
│ 1520 ┆ Генеральные подрядчики – жилое и... ┆ Генеральные подрядчики, в основн... │
│ 1711 ┆ Генеральные подрядчики по вентил... ┆ Специальные торговые подрядчики,... │
└──────┴─────────────────────────────────────┴─────────────────────────────────────┘

In [4]:
sample_submission = pl.read_parquet(f"{DATA_DIR}/sample_submission.parquet")
sample_submission.sort('transaction_dttm')

shape: (1260000, 5)
┌─────────┬──────────┬─────────────┬─────────────────┬─────────────────────┐
│ user_id ┆ mcc_code ┆ currency_rk ┆ transaction_amt ┆ transaction_dttm    │
│ ---     ┆ ---      ┆ ---         ┆ ---             ┆ ---                 │
│ i64     ┆ i64      ┆ i64         ┆ f64             ┆ str                 │
╞═════════╪══════════╪═════════════╪═════════════════╪═════════════════════╡
│ 96113   ┆ 7011     ┆ 48          ┆ -1418.5455      ┆ 2017-12-30 22:51:01 │
│ 96113   ┆ 6012     ┆ 48          ┆ 2895.265        ┆ 2018-01-03 09:33:55 │
│ 96113   ┆ 4829     ┆ 48          ┆ -1612.6825      ┆ 2018-01-04 15:50:24 │
│ 791322  ┆ 6011     ┆ 48          ┆ -214.18443      ┆ 2018-01-04 20:35:46 │
│ ...     ┆ ...      ┆ ...         ┆ ...             ┆ ...                 │
│ 507035  ┆ 7399     ┆ 48          ┆ -136.91263      ┆ 2021-08-13 18:20:20 │
│ 166516  ┆ 5411     ┆ 48          ┆ -824.3528       ┆ 2021-08-14 10:59:09 │
│ 600417  ┆ 5411     ┆ 48          ┆ -791.0856       ┆ 2021-08-14 15:29:41 │
│ 161895  ┆ 7999     ┆ 48          ┆ -76.22258       ┆ 2021-08-14 19:46:57 │
└─────────┴──────────┴─────────────┴─────────────────┴─────────────────────┘

In [12]:
# plot the distribution of the target variable
sample_submission.sample(500)

shape: (500, 5)
┌─────────┬──────────┬─────────────┬─────────────────┬─────────────────────┐
│ user_id ┆ mcc_code ┆ currency_rk ┆ transaction_amt ┆ transaction_dttm    │
│ ---     ┆ ---      ┆ ---         ┆ ---             ┆ ---                 │
│ i64     ┆ i64      ┆ i64         ┆ f64             ┆ str                 │
╞═════════╪══════════╪═════════════╪═════════════════╪═════════════════════╡
│ 617510  ┆ 5411     ┆ 48          ┆ -98.45315       ┆ 2018-04-27 10:07:28 │
│ 771948  ┆ 5999     ┆ 48          ┆ -713.2763       ┆ 2020-12-09 11:50:44 │
│ 182163  ┆ 5411     ┆ 48          ┆ -51.350018      ┆ 2021-07-16 07:37:33 │
│ 135634  ┆ 5999     ┆ 48          ┆ -706.77716      ┆ 2021-06-10 15:09:37 │
│ ...     ┆ ...      ┆ ...         ┆ ...             ┆ ...                 │
│ 428424  ┆ 5411     ┆ 48          ┆ -111.70379      ┆ 2018-11-27 03:49:29 │
│ 859521  ┆ 5814     ┆ 48          ┆ -86.56729       ┆ 2020-10-19 13:08:06 │
│ 49031   ┆ 5331     ┆ 48          ┆ -474.528        ┆ 2021-03-29 17:22:03 │
│ 365085  ┆ 5541     ┆ 48          ┆ -1215.0386      ┆ 2019-07-17 08:56:40 │
└─────────┴──────────┴─────────────┴─────────────────┴─────────────────────┘